//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public long FileSize { get; set; }
        public int UploadedByUserId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> SubmissionId { get; set; }
        public Nullable<System.DateTime> UploadedAt { get; set; }
    
        public virtual Submissions Submissions { get; set; }
        public virtual Tasks Tasks { get; set; }
        public virtual Users Users { get; set; }
    }
}
