//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaskManagementSystemEntities3 : DbContext
    {
        public TaskManagementSystemEntities3()
            : base("name=TaskManagementSystemEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Courses> Courses { get; set; }
        public DbSet<Feedback> Feedback { get; set; }
        public DbSet<Files> Files { get; set; }
        public DbSet<Notifications> Notifications { get; set; }
        public DbSet<Students> Students { get; set; }
        public DbSet<Submissions> Submissions { get; set; }
        public DbSet<Tasks> Tasks { get; set; }
        public DbSet<Teachers> Teachers { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
