//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public Students()
        {
            this.Submissions = new HashSet<Submissions>();
            this.Courses = new HashSet<Courses>();
        }
    
        public int UserId { get; set; }
        public string StudentGroup { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<Submissions> Submissions { get; set; }
        public virtual ICollection<Courses> Courses { get; set; }
    }
}
