//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submissions
    {
        public Submissions()
        {
            this.Feedback = new HashSet<Feedback>();
            this.Files = new HashSet<Files>();
            this.Notifications = new HashSet<Notifications>();
        }
    
        public int Id { get; set; }
        public int TaskId { get; set; }
        public int StudentUserId { get; set; }
        public Nullable<System.DateTime> SubmittedAt { get; set; }
        public string TextContent { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Score { get; set; }
        public string TeacherComment { get; set; }
    
        public virtual ICollection<Feedback> Feedback { get; set; }
        public virtual ICollection<Files> Files { get; set; }
        public virtual ICollection<Notifications> Notifications { get; set; }
        public virtual Students Students { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}
