//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public Tasks()
        {
            this.Files = new HashSet<Files>();
            this.Notifications = new HashSet<Notifications>();
            this.Submissions = new HashSet<Submissions>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime Deadline { get; set; }
        public Nullable<int> MaxScore { get; set; }
        public int CourseId { get; set; }
        public int TeacherUserId { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual ICollection<Files> Files { get; set; }
        public virtual ICollection<Notifications> Notifications { get; set; }
        public virtual ICollection<Submissions> Submissions { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
