//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        public Teachers()
        {
            this.Tasks = new HashSet<Tasks>();
            this.Courses = new HashSet<Courses>();
        }
    
        public int UserId { get; set; }
        public string Department { get; set; }
    
        public virtual ICollection<Tasks> Tasks { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Courses> Courses { get; set; }
    }
}
